-- MySQL Script generated by MySQL Workbench
-- Wed Nov  4 18:13:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webshop` DEFAULT CHARACTER SET utf8 ;
USE `webshop` ;

-- -----------------------------------------------------
-- Table `webshop`.`Bicikli`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`Bicikli` ;

CREATE TABLE IF NOT EXISTS `webshop`.`Bicikli` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nev` VARCHAR(255) NULL,
  `tipus` ENUM("VAROSI", "ORSZAGUTI", "TREKKING", "MTB") NULL,
  `leiras` VARCHAR(255) NULL,
  `meret` FLOAT NULL,
  `sebesseg_elol` INT NULL,
  `sebesseg_hatul` INT NULL,
  `szin` VARCHAR(255) NULL,
  `fek` VARCHAR(255) NULL,
  `teleszkop` VARCHAR(255) NULL,
  `vaz` VARCHAR(255) NULL,
  `keszlet` INT NULL,
  `netto_ar` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`Kepek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`Kepek` ;

CREATE TABLE IF NOT EXISTS `webshop`.`Kepek` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bicikli_id` INT NOT NULL,
  `kep_url` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Kepek_Bicikli_idx` (`bicikli_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Kepek_Bicikli`
    FOREIGN KEY (`bicikli_id`)
    REFERENCES `webshop`.`Bicikli` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`Users` ;

CREATE TABLE IF NOT EXISTS `webshop`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `jelszo` VARCHAR(255) NULL,
  `role` ENUM("USER", "ADMIN", "MODERATOR") NULL,
  `keresztnev` VARCHAR(255) NULL,
  `vezeteknev` VARCHAR(255) NULL,
  `telefonszam` VARCHAR(255) NULL,
  `orszag` VARCHAR(255) NULL,
  `varos` VARCHAR(255) NULL,
  `iranyitoszam` VARCHAR(20) NULL,
  `utca` VARCHAR(255) NULL,
  `hazszam` VARCHAR(20) NULL,
  `emelet` VARCHAR(20) NULL,
  `ajto` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`Rendelesek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`Rendelesek` ;

CREATE TABLE IF NOT EXISTS `webshop`.`Rendelesek` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Rendelesek_Users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Rendelesek_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `webshop`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop`.`Rendeles_tetelek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webshop`.`Rendeles_tetelek` ;

CREATE TABLE IF NOT EXISTS `webshop`.`Rendeles_tetelek` (
  `bicikli_id` INT NOT NULL,
  `rendeles_id` INT NOT NULL,
  `mennyiseg` INT NULL,
  `netto_ar` FLOAT NULL,
  `afa` INT NULL,
  INDEX `fk_Bicikli_has_Rendelesek_Rendelesek1_idx` (`rendeles_id` ASC) VISIBLE,
  INDEX `fk_Bicikli_has_Rendelesek_Bicikli1_idx` (`bicikli_id` ASC) VISIBLE,
  PRIMARY KEY (`bicikli_id`, `rendeles_id`),
  CONSTRAINT `fk_Bicikli_has_Rendelesek_Bicikli1`
    FOREIGN KEY (`bicikli_id`)
    REFERENCES `webshop`.`Bicikli` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bicikli_has_Rendelesek_Rendelesek1`
    FOREIGN KEY (`rendeles_id`)
    REFERENCES `webshop`.`Rendelesek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
